### ISSUE TITLE
Flaskサーバーが完成し次第、デプロイする

### ISSUE THREAD

**Issue by Futaba-Kosuke** [Conken-NitKit/hackz-COVID-Server#6]
デプロイは頼んだぞ！

**Comment by FukeKazki** [comment]
@Futaba-Kosuke 
Herokuの無料枠のストレージが500Mbyteまでなのに対して辞書ファイルは900Mbyteあります。

**Comment by Futaba-Kosuke** [comment]
@FukeKazki 
あっ……。……はい。。。localhostで動くように調整しますね。。。
（いくら何でも有料サーバー使うのは違うと思うので）

**Comment by Futaba-Kosuke** [comment]
Herokuデプロイできないという悲しい事実が発覚した
